"""Remove Collections

Revision ID: 1fc014ecc61f
Revises: 2c5a0aded539
Create Date: 2026-02-21 03:45:05.502423

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1fc014ecc61f"
down_revision: Union[str, Sequence[str], None] = "2c5a0aded539"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("artworks", sa.Column("images", sa.JSON(), nullable=True))
    op.drop_constraint(
        op.f("artworks_collection_id_fkey"), "artworks", type_="foreignkey"
    )
    op.drop_column("artworks", "collection_id")
    op.drop_constraint(op.f("orders_collection_id_fkey"), "orders", type_="foreignkey")
    op.drop_column("orders", "collection_id")
    op.drop_table("collections")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("collection_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("orders_collection_id_fkey"),
        "orders",
        "collections",
        ["collection_id"],
        ["id"],
    )
    op.add_column(
        "artworks",
        sa.Column("collection_id", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("artworks_collection_id_fkey"),
        "artworks",
        "collections",
        ["collection_id"],
        ["id"],
    )
    op.drop_column("artworks", "images")
    op.create_table(
        "collections",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "location", sa.VARCHAR(length=1000000), autoincrement=False, nullable=False
        ),
        sa.Column(
            "images",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("collections_pkey")),
    )
    # ### end Alembic commands ###
