"""remove materials field

Revision ID: e68981567872
Revises: 2026_04_17_limited_edition_qty
Create Date: 2026-04-17 23:19:39.324551

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e68981567872"
down_revision: Union[str, Sequence[str], None] = "2026_04_17_limited_edition_qty"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("artworks_collection_id_fkey"), "artworks", type_="foreignkey"
    )
    op.drop_table("collections")
    op.drop_column("artworks", "materials")
    op.drop_column("artworks", "collection_id")
    op.drop_constraint(op.f("labels_category_id_fkey"), "labels", type_="foreignkey")
    op.create_foreign_key(
        None, "labels", "label_categories", ["category_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "print_pricing",
        "print_type",
        existing_type=sa.VARCHAR(length=30),
        comment="canvas | canvas_limited | paper | paper_limited",
        existing_nullable=False,
    )
    op.alter_column(
        "print_pricing",
        "size_label",
        existing_type=sa.VARCHAR(length=50),
        comment='Human-readable size string, e.g. "30×40 cm" or "12×16 in"',
        existing_nullable=False,
    )
    op.alter_column(
        "print_pricing",
        "price",
        existing_type=sa.INTEGER(),
        comment="Price in whole USD",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "print_pricing",
        "price",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Price in whole USD",
        existing_nullable=False,
    )
    op.alter_column(
        "print_pricing",
        "size_label",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment='Human-readable size string, e.g. "30×40 cm" or "12×16 in"',
        existing_nullable=False,
    )
    op.alter_column(
        "print_pricing",
        "print_type",
        existing_type=sa.VARCHAR(length=30),
        comment=None,
        existing_comment="canvas | canvas_limited | paper | paper_limited",
        existing_nullable=False,
    )
    op.drop_constraint(None, "labels", type_="foreignkey")
    op.create_foreign_key(
        op.f("labels_category_id_fkey"),
        "labels",
        "label_categories",
        ["category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "artworks",
        sa.Column("collection_id", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "artworks",
        sa.Column(
            "materials", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        op.f("artworks_collection_id_fkey"),
        "artworks",
        "collections",
        ["collection_id"],
        ["id"],
    )
    op.create_table(
        "collections",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("collections_pkey")),
        sa.UniqueConstraint(
            "title",
            name=op.f("collections_title_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
