"""split_artist_photo

Revision ID: 7586352b64fd
Revises: 010d6ef7ec14
Create Date: 2026-03-31 14:49:59.746312

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7586352b64fd"
down_revision: Union[str, Sequence[str], None] = "010d6ef7ec14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "site_settings",
        sa.Column("artist_home_photo_url", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "site_settings",
        sa.Column("artist_about_photo_url", sa.String(length=500), nullable=True),
    )
    op.drop_column("site_settings", "artist_photo_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "site_settings",
        sa.Column(
            "artist_photo_url",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("site_settings", "artist_about_photo_url")
    op.drop_column("site_settings", "artist_home_photo_url")
    # ### end Alembic commands ###
