"""replace_print_fields_with_has_prints_and_add_orientation

Revision ID: deb9e26c9c6a
Revises: d9016c975290
Create Date: 2026-04-01 23:32:02.903329

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "deb9e26c9c6a"
down_revision: Union[str, Sequence[str], None] = "d9016c975290"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("artworks", sa.Column("has_prints", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column(
        "artworks", sa.Column("orientation", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "artworks", sa.Column("base_print_price", sa.Integer(), nullable=True)
    )
    op.drop_column("artworks", "prints_total")
    op.drop_column("artworks", "is_display_only")
    op.drop_column("artworks", "prints_available")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "artworks",
        sa.Column(
            "prints_available",
            sa.INTEGER(),
            server_default=sa.text("27"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "artworks",
        sa.Column(
            "is_display_only",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "artworks",
        sa.Column(
            "prints_total",
            sa.INTEGER(),
            server_default=sa.text("27"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("artworks", "base_print_price")
    op.drop_column("artworks", "orientation")
    op.drop_column("artworks", "has_prints")
    # ### end Alembic commands ###
