"""payment_fields

Revision ID: 89f9970e642f
Revises: 2f053f4dec79
Create Date: 2026-03-13 23:49:52.196624

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "89f9970e642f"
down_revision: Union[str, Sequence[str], None] = "2f053f4dec79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("artwork_id", sa.Integer(), nullable=False),
        sa.Column("edition_type", sa.String(length=20), nullable=False),
        sa.Column("finish", sa.String(length=50), nullable=False),
        sa.Column("size", sa.String(length=50), nullable=True),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artwork_id"],
            ["artworks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "orders", sa.Column("first_name", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "orders", sa.Column("last_name", sa.String(length=100), nullable=False)
    )
    op.add_column("orders", sa.Column("email", sa.String(length=200), nullable=False))
    op.add_column("orders", sa.Column("phone", sa.String(length=50), nullable=False))
    op.add_column(
        "orders", sa.Column("newsletter_opt_in", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "orders", sa.Column("discovery_source", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("promo_code", sa.String(length=50), nullable=True)
    )
    op.add_column("orders", sa.Column("total_price", sa.Integer(), nullable=False))
    op.add_column(
        "orders", sa.Column("payment_status", sa.String(length=20), nullable=False)
    )
    op.add_column(
        "orders", sa.Column("invoice_id", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("payment_url", sa.String(length=500), nullable=True)
    )
    op.alter_column("orders", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(op.f("orders_artwork_id_fkey"), "orders", type_="foreignkey")
    op.drop_column("orders", "price")
    op.drop_column("orders", "artwork_id")
    op.drop_column("orders", "edition_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "edition_type",
            sa.VARCHAR(length=20),
            server_default=sa.text("'original'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "orders",
        sa.Column("artwork_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "orders", sa.Column("price", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key(
        op.f("orders_artwork_id_fkey"), "orders", "artworks", ["artwork_id"], ["id"]
    )
    op.alter_column("orders", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("orders", "payment_url")
    op.drop_column("orders", "invoice_id")
    op.drop_column("orders", "payment_status")
    op.drop_column("orders", "total_price")
    op.drop_column("orders", "promo_code")
    op.drop_column("orders", "discovery_source")
    op.drop_column("orders", "newsletter_opt_in")
    op.drop_column("orders", "phone")
    op.drop_column("orders", "email")
    op.drop_column("orders", "last_name")
    op.drop_column("orders", "first_name")
    op.drop_table("order_items")
    # ### end Alembic commands ###
