"""add bg color to collections

Revision ID: 010d6ef7ec14
Revises: a7f42a6be602
Create Date: 2026-03-15 01:17:45.189962

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "010d6ef7ec14"
down_revision: Union[str, Sequence[str], None] = "a7f42a6be602"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collections", sa.Column("bg_color", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collections", "bg_color")
    # ### end Alembic commands ###
