"""global_print_price

Revision ID: f60569e29f5d
Revises: 0ef00aecb7ff
Create Date: 2026-03-14 21:54:47.493380

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f60569e29f5d"
down_revision: Union[str, Sequence[str], None] = "0ef00aecb7ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("artworks", "print_price")
    # Add column as nullable first
    op.add_column(
        "site_settings", sa.Column("global_print_price", sa.Integer(), nullable=True)
    )
    # Set default value for existing rows
    op.execute("UPDATE site_settings SET global_print_price = 150")
    # Make it NOT NULL
    op.alter_column("site_settings", "global_print_price", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("site_settings", "global_print_price")
    op.add_column(
        "artworks",
        sa.Column("print_price", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
