"""tags_to_labels

Revision ID: c6fea1af7f24
Revises: a1b2c3d4e5f6
Create Date: 2026-04-16 17:34:01.329397

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c6fea1af7f24"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "label_categories",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("accent_color", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "labels",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"], ["label_categories.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "artwork_labels",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("artwork_id", sa.BigInteger(), nullable=False),
        sa.Column("label_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["artwork_id"], ["artworks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["label_id"], ["labels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    
    # --- DATA MIGRATION ---
    conn = op.get_bind()
    
    # 1. Migrate distinct categories
    conn.execute(sa.text("""
        INSERT INTO label_categories (title)
        SELECT DISTINCT category FROM tags WHERE category IS NOT NULL AND category != ''
    """))
    
    # 2. Migrate tags to labels
    conn.execute(sa.text("""
        INSERT INTO labels (id, title, category_id)
        SELECT t.id, t.title, c.id
        FROM tags t
        LEFT JOIN label_categories c ON t.category = c.title
    """))
    
    # 3. Fix sequence for labels since we copied ids Manually Postgres only
    # To be extremely safe, we advance the sequence for postgres:
    conn.execute(sa.text("SELECT setval('labels_id_seq', COALESCE((SELECT MAX(id)+1 FROM labels), 1), false)"))
    
    # 4. Migrate artwork_tags to artwork_labels
    conn.execute(sa.text("""
        INSERT INTO artwork_labels (id, artwork_id, label_id)
        SELECT id, artwork_id, tag_id FROM artwork_tags
    """))
    conn.execute(sa.text("SELECT setval('artwork_labels_id_seq', COALESCE((SELECT MAX(id)+1 FROM artwork_labels), 1), false)"))
    
    # --- END DATA MIGRATION ---
    op.drop_table("artwork_tags")
    op.drop_table("tags")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column(
            "id",
            sa.BIGINT(),
            server_default=sa.text("nextval('tags_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "category", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="tags_pkey"),
        sa.UniqueConstraint(
            "title",
            name="tags_title_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "artwork_tags",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("artwork_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("tag_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["artwork_id"], ["artworks.id"], name=op.f("artwork_tags_artwork_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("artwork_tags_tag_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("artwork_tags_pkey")),
    )
    op.drop_table("artwork_labels")
    op.drop_table("labels")
    op.drop_table("label_categories")
    # ### end Alembic commands ###
