"""add_print_aspect_ratios_and_artwork_print_config

Revision ID: 8ed5d34ea719
Revises: e68981567872
Create Date: 2026-04-17 23:52:31.406512

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8ed5d34ea719"
down_revision: Union[str, Sequence[str], None] = "e68981567872"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "print_aspect_ratios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label"),
    )
    op.add_column(
        "artworks", sa.Column("print_aspect_ratio_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "artworks",
        sa.Column("print_min_size_label", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "artworks",
        sa.Column("print_max_size_label", sa.String(length=50), nullable=True),
    )
    op.create_index(
        op.f("ix_artworks_print_aspect_ratio_id"),
        "artworks",
        ["print_aspect_ratio_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "artworks",
        "print_aspect_ratios",
        ["print_aspect_ratio_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "print_pricing",
        # Add as nullable first so existing rows (without an aspect ratio) don't cause
        # a constraint violation. We then delete those orphaned rows and flip to NOT NULL.
        sa.Column("aspect_ratio_id", sa.Integer(), nullable=True),
    )
    op.create_index(
        op.f("ix_print_pricing_aspect_ratio_id"),
        "print_pricing",
        ["aspect_ratio_id"],
        unique=False,
    )

    # Remove any legacy pricing rows that cannot be assigned to an aspect ratio.
    # This is expected: the admin will re-create the grid via the new UI.
    op.execute("DELETE FROM print_pricing WHERE aspect_ratio_id IS NULL")

    # Now that all remaining rows have a valid aspect_ratio_id, enforce NOT NULL.
    op.alter_column("print_pricing", "aspect_ratio_id", nullable=False)

    op.create_foreign_key(
        None,
        "print_pricing",
        "print_aspect_ratios",
        ["aspect_ratio_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "print_pricing", type_="foreignkey")
    op.drop_index(op.f("ix_print_pricing_aspect_ratio_id"), table_name="print_pricing")
    op.drop_column("print_pricing", "aspect_ratio_id")
    op.drop_constraint(None, "artworks", type_="foreignkey")
    op.drop_index(op.f("ix_artworks_print_aspect_ratio_id"), table_name="artworks")
    op.drop_column("artworks", "print_max_size_label")
    op.drop_column("artworks", "print_min_size_label")
    op.drop_column("artworks", "print_aspect_ratio_id")
    op.drop_table("print_aspect_ratios")
    # ### end Alembic commands ###
