"""add footer settings

Revision ID: 265837a4c028
Revises: f5cfcb32bb61
Create Date: 2026-04-13 01:17:13.390826

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "265837a4c028"
down_revision: Union[str, Sequence[str], None] = "f5cfcb32bb61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "site_settings",
        sa.Column("social_instagram", sa.String(length=200), nullable=True),
    )
    op.add_column(
        "site_settings",
        sa.Column("social_telegram", sa.String(length=200), nullable=True),
    )
    op.add_column(
        "site_settings",
        sa.Column("social_threads", sa.String(length=200), nullable=True),
    )
    op.add_column(
        "site_settings", sa.Column("footer_text_discover", sa.Text(), nullable=True)
    )
    op.add_column(
        "site_settings", sa.Column("footer_text_services", sa.Text(), nullable=True)
    )
    op.add_column(
        "site_settings", sa.Column("footer_text_circle", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("site_settings", "footer_text_circle")
    op.drop_column("site_settings", "footer_text_services")
    op.drop_column("site_settings", "footer_text_discover")
    op.drop_column("site_settings", "social_threads")
    op.drop_column("site_settings", "social_telegram")
    op.drop_column("site_settings", "social_instagram")
    # ### end Alembic commands ###
