"""site_settings_table

Revision ID: 94b552a0cdd1
Revises: cadba2e5a68a
Create Date: 2026-03-14 19:31:59.619640

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "94b552a0cdd1"
down_revision: Union[str, Sequence[str], None] = "cadba2e5a68a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("about_text", sa.Text(), nullable=True),
        sa.Column("contact_email", sa.String(length=200), nullable=True),
        sa.Column("artist_photo_url", sa.String(length=500), nullable=True),
        sa.Column("main_bg_url", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("site_settings")
    # ### end Alembic commands ###
