"""responsive bg

Revision ID: 0ef00aecb7ff
Revises: 94b552a0cdd1
Create Date: 2026-03-14 21:23:45.059099

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0ef00aecb7ff"
down_revision: Union[str, Sequence[str], None] = "94b552a0cdd1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "site_settings",
        sa.Column("main_bg_desktop_url", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "site_settings",
        sa.Column("main_bg_mobile_url", sa.String(length=500), nullable=True),
    )
    op.drop_column("site_settings", "main_bg_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "site_settings",
        sa.Column(
            "main_bg_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("site_settings", "main_bg_mobile_url")
    op.drop_column("site_settings", "main_bg_desktop_url")
    # ### end Alembic commands ###
