"""add_artwork_slug

Revision ID: 30f520bafda1
Revises: add_slide_duration
Create Date: 2026-04-02 19:15:40.929455

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "30f520bafda1"
down_revision: Union[str, Sequence[str], None] = "add_slide_duration"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


import re

def slugify(text: str) -> str:
    if not text: return "artwork"
    text = text.lower()
    text = re.sub(r'[^a-z0-9]+', '-', text)
    return text.strip('-')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("artworks", sa.Column("slug", sa.String(length=255), nullable=True))
    
    # Populate existing rows
    connection = op.get_bind()
    artworks_data = connection.execute(sa.text("SELECT id, title FROM artworks")).fetchall()
    for row in artworks_data:
        base_slug = slugify(row[1])
        slug = f"{row[0]}-{base_slug}"
        connection.execute(
            sa.text("UPDATE artworks SET slug = :slug WHERE id = :id"),
            {"slug": slug, "id": row[0]}
        )
    
    op.create_index(op.f("ix_artworks_slug"), "artworks", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_artworks_slug"), table_name="artworks")
    op.drop_column("artworks", "slug")
    # ### end Alembic commands ###
