"""Add prodigi columns to order_items

Revision ID: a6c293af7cfb
Revises: 8ed5d34ea719
Create Date: 2026-04-19 21:13:06.645732

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a6c293af7cfb"
down_revision: Union[str, Sequence[str], None] = "8ed5d34ea719"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_items", sa.Column("prodigi_attributes", sa.JSON(), nullable=True)
    )
    op.add_column(
        "order_items",
        sa.Column("prodigi_shipping_method", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "order_items",
        sa.Column("prodigi_order_id", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "order_items", sa.Column("prodigi_status", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "order_items", sa.Column("prodigi_wholesale_eur", sa.Float(), nullable=True)
    )
    op.add_column(
        "order_items", sa.Column("prodigi_shipping_eur", sa.Float(), nullable=True)
    )
    op.add_column(
        "order_items", sa.Column("prodigi_retail_eur", sa.Float(), nullable=True)
    )
    op.alter_column(
        "order_items",
        "prodigi_sku",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order_items",
        "prodigi_sku",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.drop_column("order_items", "prodigi_retail_eur")
    op.drop_column("order_items", "prodigi_shipping_eur")
    op.drop_column("order_items", "prodigi_wholesale_eur")
    op.drop_column("order_items", "prodigi_status")
    op.drop_column("order_items", "prodigi_order_id")
    op.drop_column("order_items", "prodigi_shipping_method")
    op.drop_column("order_items", "prodigi_attributes")
    # ### end Alembic commands ###
