"""Add edition columns and redesign artworks

Revision ID: f7e37134e10a
Revises: 38cbe15c2a55
Create Date: 2026-02-21 02:59:17.635063

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f7e37134e10a"
down_revision: Union[str, Sequence[str], None] = "38cbe15c2a55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "artworks", sa.Column("is_display_only", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("artworks", sa.Column("original_price", sa.Integer(), nullable=True))
    op.add_column(
        "artworks", sa.Column("is_original_available", sa.Boolean(), server_default="true", nullable=False)
    )
    op.add_column("artworks", sa.Column("print_price", sa.Integer(), nullable=True))
    op.add_column("artworks", sa.Column("prints_total", sa.Integer(), server_default="27", nullable=False))
    op.add_column(
        "artworks", sa.Column("prints_available", sa.Integer(), server_default="27", nullable=False)
    )
    op.drop_column("artworks", "quantity")
    op.drop_column("artworks", "price")
    op.add_column(
        "orders", sa.Column("edition_type", sa.String(length=20), server_default="original", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "edition_type")
    op.add_column(
        "artworks",
        sa.Column("price", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "artworks",
        sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("artworks", "prints_available")
    op.drop_column("artworks", "prints_total")
    op.drop_column("artworks", "print_price")
    op.drop_column("artworks", "is_original_available")
    op.drop_column("artworks", "original_price")
    op.drop_column("artworks", "is_display_only")
    # ### end Alembic commands ###
