"""add_shipping_address_fields

Revision ID: f5cfcb32bb61
Revises: 248e27e489cc
Create Date: 2026-04-10 01:30:48.506747

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f5cfcb32bb61"
down_revision: Union[str, Sequence[str], None] = "248e27e489cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("shipping_country", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("shipping_country_code", sa.String(length=2), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("shipping_state", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("shipping_city", sa.String(length=200), nullable=True)
    )
    op.add_column(
        "orders",
        sa.Column("shipping_address_line1", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "orders",
        sa.Column("shipping_address_line2", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "orders", sa.Column("shipping_postal_code", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("shipping_phone", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "orders", sa.Column("shipping_notes", sa.String(length=1000), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "shipping_notes")
    op.drop_column("orders", "shipping_phone")
    op.drop_column("orders", "shipping_postal_code")
    op.drop_column("orders", "shipping_address_line2")
    op.drop_column("orders", "shipping_address_line1")
    op.drop_column("orders", "shipping_city")
    op.drop_column("orders", "shipping_state")
    op.drop_column("orders", "shipping_country_code")
    op.drop_column("orders", "shipping_country")
    # ### end Alembic commands ###
