"""Add print_quality_url to artworks

Revision ID: 9ac9db18866e
Revises: a6c293af7cfb
Create Date: 2026-04-19 21:15:36.269653

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ac9db18866e"
down_revision: Union[str, Sequence[str], None] = "a6c293af7cfb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "artworks",
        sa.Column("print_quality_url", sa.String(length=1000), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("artworks", "print_quality_url")
    # ### end Alembic commands ###
