"""re-add collections

Revision ID: ced55b45b464
Revises: f60569e29f5d
Create Date: 2026-03-14 22:34:35.350187

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ced55b45b464"
down_revision: Union[str, Sequence[str], None] = "f60569e29f5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collections",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.add_column(
        "artworks", sa.Column("collection_id", sa.BigInteger(), nullable=True)
    )
    op.create_foreign_key(None, "artworks", "collections", ["collection_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "artworks", type_="foreignkey")
    op.drop_column("artworks", "collection_id")
    op.drop_table("collections")
    # ### end Alembic commands ###
