"""Add prodigi columns to order_items

Revision ID: a6c293af7cfb
Revises: 8ed5d34ea719
Create Date: 2026-04-19 21:13:06.645732

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6c293af7cfb"
down_revision: Union[str, Sequence[str], None] = "8ed5d34ea719"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_column(table_name: str, column_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return any(column["name"] == column_name for column in inspector.get_columns(table_name))


def _add_order_item_column_if_missing(column: sa.Column) -> None:
    if not _has_column("order_items", column.name):
        op.add_column("order_items", column)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _add_order_item_column_if_missing(
        sa.Column("prodigi_sku", sa.String(length=100), nullable=True)
    )
    _add_order_item_column_if_missing(sa.Column("prodigi_attributes", sa.JSON(), nullable=True))
    _add_order_item_column_if_missing(
        sa.Column("prodigi_shipping_method", sa.String(length=50), nullable=True),
    )
    _add_order_item_column_if_missing(
        sa.Column("prodigi_order_id", sa.String(length=100), nullable=True),
    )
    _add_order_item_column_if_missing(
        sa.Column("prodigi_status", sa.String(length=50), nullable=True)
    )
    _add_order_item_column_if_missing(sa.Column("prodigi_wholesale_eur", sa.Float(), nullable=True))
    _add_order_item_column_if_missing(sa.Column("prodigi_shipping_eur", sa.Float(), nullable=True))
    _add_order_item_column_if_missing(sa.Column("prodigi_retail_eur", sa.Float(), nullable=True))
    op.alter_column(
        "order_items",
        "prodigi_sku",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if _has_column("order_items", "prodigi_sku"):
        op.alter_column(
            "order_items",
            "prodigi_sku",
            existing_type=sa.String(length=100),
            type_=sa.VARCHAR(length=50),
            existing_nullable=True,
        )
    for column_name in (
        "prodigi_retail_eur",
        "prodigi_shipping_eur",
        "prodigi_wholesale_eur",
        "prodigi_status",
        "prodigi_order_id",
        "prodigi_shipping_method",
        "prodigi_attributes",
    ):
        if _has_column("order_items", column_name):
            op.drop_column("order_items", column_name)
    # ### end Alembic commands ###
