"""Add artwork characteristics

Revision ID: a7f42a6be602
Revises: ced55b45b464
Create Date: 2026-03-15 00:57:57.460554

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a7f42a6be602"
down_revision: Union[str, Sequence[str], None] = "ced55b45b464"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("artworks", sa.Column("year", sa.Integer(), nullable=True))
    op.add_column(
        "artworks", sa.Column("materials", sa.String(length=200), nullable=True)
    )
    op.add_column("artworks", sa.Column("style", sa.String(length=100), nullable=True))
    op.add_column("artworks", sa.Column("width_cm", sa.Float(), nullable=True))
    op.add_column("artworks", sa.Column("height_cm", sa.Float(), nullable=True))
    op.add_column("artworks", sa.Column("depth_cm", sa.Float(), nullable=True))
    op.add_column("artworks", sa.Column("width_in", sa.Float(), nullable=True))
    op.add_column("artworks", sa.Column("height_in", sa.Float(), nullable=True))
    op.add_column("artworks", sa.Column("depth_in", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("artworks", "depth_in")
    op.drop_column("artworks", "height_in")
    op.drop_column("artworks", "width_in")
    op.drop_column("artworks", "depth_cm")
    op.drop_column("artworks", "height_cm")
    op.drop_column("artworks", "width_cm")
    op.drop_column("artworks", "style")
    op.drop_column("artworks", "materials")
    op.drop_column("artworks", "year")
    # ### end Alembic commands ###
