"""refactored orders for shop logic

Revision ID: 38cbe15c2a55
Revises: a0a84025b0af
Create Date: 2026-02-19 23:06:12.637766

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "38cbe15c2a55"
down_revision: Union[str, Sequence[str], None] = "a0a84025b0af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.drop_column("orders", "check_out_date")
    op.drop_column("orders", "check_in_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "check_in_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "orders",
        sa.Column(
            "check_out_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("orders", "created_at")
    # ### end Alembic commands ###
